### ISSUE TITLE
windows chromium54

### ISSUE THREAD

**Issue by bridiver** [brave/muon#95]
## milestones
- [x] get project compiling
- [x] get project linking
- [x] build / upload binaries for ia32 + x64

## hacks made along the way (in need of proper fixing)
- [ ] widevine is disabled
  - related https://github.com/brave/electron/commit/7bd7715b65a5d3b06609268dfe4eec4da8b193ee
- [ ] printing may or may not work
- [ ] chrome_constants - EXECUTABLE_NAME issue (worked around by putting "Brave.exe")
- [ ] Brave_paths.cc - Changed ATOM_PROJECT_NAME to FPL("brave")
- [x] non cmd.exe Path issue
- [x] Hardcoded release as x64 https://github.com/brave/electron/commit/0a80b9507f7d79dc33698658738673770f1e39d4

**Comment by bsclifton** [comment]
updated with notes from today :smile:
